language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: BDkNjR5t/DCVrhm19piUEhcQQRS8OOnelhKfS2OajEti2WZwG36ImSlhPh7UifE+JIk7KEpFeHn2FDOr9HTGeenh6OAc8AbSlavV09mZpB4VQY/jxs3AwWr3F7KnYeLdBE4gAl6HdgUQ3oI0aE8Li+oxqRynNhpJmmDk/6Ydwz3Gr3DMr45b+3S4qEWFg30MLzOk6SzyaeK4HUFLphxmy/4OQ6Is0zIM08dGpfYSAvUPyWKWYX//1ftmEBUEXx/BlUxakn+2pbez2faUn1eGMiEFotQbUhYbhgxom69Y7bA/D0zwz6mTyE3qUP9ahgpwLWfVT638TAFSL7VVk+osovWEW+NrvdlRtpbJodZiV5gxeFJkwBSbyKb1fWnAxc57Djyqeo8s+hEv/e7YwKizkOAMEmbKydNGFt9TiX27FvNYIXQqkJRTu4Phk+za34Xi1tqFKu318p6YxxTBsJ4Tk0Ks1YAgVh7bklMH4RJxKgvvUCibw2+HPGFA3jvNo8wigAY1zCwEoBH/hiySLw31uvNdrei4z2vQ/eDuSUDyfPnZ9EJG1pAV32+kuVJQavK4qUDC5cqCbPWNu+rpWK+vPt1bxlVlEtcu3koDJwQmVSVi1P3s9CGP3eiGpd4zaMJphn8BIwsdid/0v4dIEjRCKgb0uzlQVtg0pSlSILqCbOA=
  on:
    tags: true
    repo: sriki18/bib_cleaner
    python: 3.8
